CFLAGS=-Wall -O0  -g


clean:

	rm -f ex1
	rm -f ex2
	rm -f ex3
all:
	cc -Wall -O0 -g ex1.c -o ex1
	cc -Wall -O0 -g ex2.c -o ex2
	cc -Wall -O0 -g ex3.c -o ex3
	cc -Wall -O0 -g ex7.c -o ex7
	cc -Wall -O0 -g ex8.c -o ex8
	cc -Wall -O0 -g ex9.c -o ex9
	cc -Wall -O0 -g ex10.c -o ex10
	cc -Wall -O0 -g ex11.c -o ex11
	cc -Wall -O0 -g ex12.c -o ex12
	cc -Wall -O0 -g ex7.c -o ex7
	cc -Wall -O0 -g ex7.c -o ex7
	cc -Wall -O0 -g ex7.c -o ex7
	cc -Wall -O0 -g ex7.c -o ex7
	cc -Wall -O0 -g ex7.c -o ex7
	cc -Wall -O0 -g ex7.c -o ex7
	cc -Wall -O0 -g ex7.c -o ex7
